Repository chiflix/splayerx, pull requests merged in 2018-07, with the labels that each got.

#52 Landing view
  src/main/index.js
  src/renderer/assets/Noise.png
  src/renderer/components/LandingView.vue
  src/renderer/components/PlayingView/VideoCanvas.vue
  src/renderer/helpers/index.js
Labels: invalid

#57 Bugs: Fix Appveyor and Travis.ci build failure
  package.json
Labels: help wanted

#61 修复electron-builder更新到最新版打包报错的问题
  package.json
Labels: question
