Repository chiflix/splayerx, pull requests merged in 2019-07, with the labels that each got.

#763 fix(subtitle): use mediaHash to store subtitle preferences
  src/main/helpers/mediaTasksPlugin.ts
  src/renderer/containers/LandingView.vue
  src/renderer/containers/VideoCanvas.vue
  src/renderer/interfaces/ISubtitleStorage.ts
  src/renderer/services/storage/subtitle/db.ts
  src/renderer/services/storage/subtitle/index.ts
  src/renderer/store/modules/Subtitle.ts
  src/renderer/store/modules/SubtitleManager.ts
  src/renderer/store/mutationTypes.js
Labels: bug, refactor

#766 style(subtitlecontrol): keep secondary subtitle size when no primary subtitle
  src/renderer/components/PlayingView/SubtitleControl.vue
  src/renderer/components/Subtitle/SubtitleRenderer.vue
Labels: enhancement

#642 feat(traing): traing audio to subtitle
  .electron-vue/webpack.main.config.js
  .electron-vue/webpack.renderer.config.js
  package.json
  src/main/helpers/AudioGrabService.ts
  src/main/helpers/mediaTasksPlugin.ts
  src/main/index.js
  src/renderer/assets/icon/complete-active-icon.svg
  src/renderer/assets/icon/complete-default-icon.svg
  src/renderer/assets/icon/complete-hover-icon.svg
  src/renderer/assets/icon/restart-active-icon.svg
  src/renderer/assets/icon/restart-default-icon.svg
  src/renderer/assets/icon/restart-hover-icon.svg
  src/renderer/components/NotificationBubble.vue
  src/renderer/components/PlayingView.vue
  src/renderer/components/PlayingView/BaseVideoPlayer.vue
  src/renderer/components/PlayingView/Progress.vue
  src/renderer/components/PlayingView/Select.vue
  src/renderer/components/PlayingView/SubtitleControl.vue
  src/renderer/components/PlayingView/SubtitleList.vue
  src/renderer/components/PlayingView/TranslateBubble.vue
  src/renderer/components/Preferences/General.vue
  src/renderer/components/Preferences/Privacy.vue
  src/renderer/components/Welcome/Dropdown.vue
  src/renderer/containers/AdvanceMainMenu.vue
  src/renderer/containers/AudioTranslateModal.vue
  src/renderer/containers/TheVideoController.vue
  src/renderer/containers/VideoCanvas.vue
  src/renderer/helpers/index.js
  src/renderer/helpers/notificationControl.js
  src/renderer/helpers/notificationcodes.js
  src/renderer/interfaces/IMediaStorable.ts
  src/renderer/interfaces/ISubtitle.ts
  src/renderer/libs/CacheFile.ts
  src/renderer/libs/sagi.ts
  src/renderer/libs/utils.ts
  src/renderer/locales/lang/en.json
  src/renderer/main.ts
  src/renderer/services/media/AudioTranslateService.ts
  src/renderer/services/storage/MediaStorageService.ts
  src/renderer/services/storage/subtitle/index.ts
  src/renderer/services/subtitle/loaders/index.ts
  src/renderer/services/subtitle/loaders/online.ts
  src/renderer/services/subtitle/loaders/translated.ts
  src/renderer/services/subtitle/utils/index.ts
  src/renderer/store/actionTypes.js
  src/renderer/store/modules/AudioTranslate.ts
  src/renderer/store/modules/Input.js
  src/renderer/store/modules/Subtitle.ts
  src/renderer/store/modules/SubtitleManager.ts
  src/renderer/store/modules/Video.js
  src/renderer/store/mutationTypes.js
  src/renderer/typings.d.ts
  test/unit/specs/services/media/AudioTranslateService.spec.js
Labels: enhancement

#769 fix(translate): fix progress && show ai subtitle
  src/main/helpers/AudioGrabService.ts
  src/renderer/libs/sagi.ts
  src/renderer/locales/lang/en.json
  src/renderer/services/media/AudioTranslateService.ts
  src/renderer/services/storage/subtitle/index.ts
  src/renderer/store/modules/AudioTranslate.ts
  src/renderer/store/modules/SubtitleManager.ts
Labels: enhancement

#771 Feature switch
  package.json
  src/renderer/containers/LandingView.vue
  src/renderer/helpers/featureSwitch.ts
  src/renderer/libs/utils.ts
  src/renderer/main.ts
  src/renderer/store/modules/SubtitleManager.ts
  test/unit/specs/libs/utils.spec.js
Labels: enhancement

#758 refactor: Menu
  .eslintrc.js
  src/main/index.js
  src/main/menu/Menu.ts
  src/main/menu/MenuService.ts
  src/main/menu/common/Menubar.ts
  src/main/menu/menu.json
  src/main/window/WindowService.ts
  src/renderer/containers/TheVideoController.vue
  src/renderer/interfaces/IRecentPlay.ts
  src/renderer/locales/index.js
  src/renderer/locales/lang/en.json
  src/renderer/main.ts
  src/renderer/services/media/RecentPlayService.ts
  src/renderer/services/menu/MenuService.ts
  src/renderer/services/window/WindowRectService.ts
  src/shared/common/localize.ts
  src/shared/common/platform.ts
Labels: refactor

#761 feat: Nsfw
  package.json
  src/main/helpers/mediaTasksPlugin.ts
  src/main/index.js
  src/main/menu/Menu.ts
  src/renderer/assets/icon/radio-default-icon.svg
  src/renderer/components/BaseIconContainer.vue
  src/renderer/components/LandingView/PlaylistItem.vue
  src/renderer/components/LandingView/VideoItem.vue
  src/renderer/components/NotificationBubble.vue
  src/renderer/components/PlayingView/NSFW.vue
  src/renderer/components/Preference.vue
  src/renderer/components/Preferences/BaseRadio.vue
  src/renderer/components/Preferences/General.vue
  src/renderer/components/Preferences/Privacy.vue
  src/renderer/components/Preferences/Translate.vue
  src/renderer/containers/LandingView.vue
  src/renderer/containers/RecentPlaylist.vue
  src/renderer/containers/RecentPlaylistItem.vue
  src/renderer/containers/VideoCanvas.vue
  src/renderer/interfaces/IMediaFilter.ts
  src/renderer/locales/lang/ar.json
  src/renderer/locales/lang/en.json
  src/renderer/locales/lang/es.json
  src/renderer/locales/lang/ja.json
  src/renderer/locales/lang/ko.json
  src/renderer/locales/lang/zh-Hans.json
  src/renderer/locales/lang/zh-Hant.json
  src/renderer/main.ts
  src/renderer/preference.js
  src/renderer/services/filter/NSFWThumbnailFilterService.ts
  src/renderer/store/modules/Preference.js
  static/cursor/cursorLeft.svg
  static/cursor/cursorRight.svg
  static/nsfw/group1-shard1of1
  static/nsfw/model.json
Labels: enhancement
